export enum CategoryType {
  ASET = 'ASET',
  KEWAJIBAN = 'KEWAJIBAN',
  MODAL = 'MODAL',
  PENDAPATAN = 'PENDAPATAN',
  BEBAN = 'BEBAN',
  INVESTASI = 'INVESTASI',
  PENDANAAN = 'PENDANAAN',
  OPERASIONAL = 'OPERASIONAL',
}
